Added a SocketAddr struct to the return signature of Udp.receive
rust-embedded-community/embedded-nal pull request #22
Opened 2020-11-11 06:19 UTC by jonahd-g

2020-11-12 08:57 UTC, ryan-summers requested changes
This follows from standard UDP communication, so I think it's a good change. Users who do not care about the source socket address can simply ignore the value.

TODO:
- [x] Add a changelog entry for the new return value

2020-11-13 22:37 UTC, jonahd-g commented
- [x] Add a changelog entry for the new return value

2020-11-14 10:42 UTC, ryan-summers approved these changes

2020-11-14 15:05 UTC, MathiasKoch approved these changes

2020-11-14 19:36 UTC, eldruin approved these changes

2020-11-14 19:37 UTC, merged