Removed Internal Mutability
rust-embedded-community/embedded-nal pull request #42
Opened 2021-01-17 22:07 UTC by jonahd-g

Removed requirement on internal mutability by using mutable self references in methods.

See #39 for details.  Should not be merged unless that alternate approach to sharing is approved.

2021-01-18 09:21 UTC, ryan-summers commented
I agree with your point about internal mutability being required and the existing API not guaranteeing thread safety, and thus, I am on board with this. @MathiasKoch thoughts?

2021-01-18 09:26 UTC, MathiasKoch commented
I think this is okay, assuming we can reach some agreement on #39 as stated in OP

2021-01-18 23:05 UTC, thejpster approved these changes

2021-01-19 06:17 UTC, ryan-summers approved these changes

2021-01-19 06:18 UTC, ryan-summers requested changes
Ah just noticed missing CHANGELOG entry. Mind adding a notice there that we're adding self mutability and reference issue #39 for more detail?

2021-01-19 08:51 UTC, eldruin approved these changes
I agree with this way forward.
Other than the changelog entry, looks good to me. Thanks!

2021-01-19 09:12 UTC, MathiasKoch approved these changes

2021-01-19 18:02 UTC, ryan-summers approved these changes
Thanks! :)

2021-01-19 18:02 UTC, jonahd-g commented
Thanks Ryan.  I keep forgetting too, maybe we need an Action to check for that.

Changelog entry added.

2021-01-19 18:03 UTC, merged